# generate a simple github actions demo like listing the files in the current directory
name: List Files
on:
  push:
    branches:
      - main

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: |
          echo "Listing files in the current directory:"
          ls -al
          echo "Count lines in README.md:"
          if [ -f README.md ]; then
            wc -l README.md
          else
            echo "README.md not found"
          fi
