# generate a job 2 that depends on job 1
name: Job Dependency Example
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print date and time for job1
        run: |
          echo "Job1 started at:"
          date
      - name: List smallest file
        run: |
          echo "Finding the smallest file in the repository:"
          find . -type f -exec du -b {} + | sort -n | head -n 1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print date and time for job2
        run: |
          echo "Job2 started at:"
          date
      - name: List largest file
        run: |
          echo "Finding the largest file in the repository:"
          find . -type f -exec du -b {} + | sort -n | tail -n 1
