# generate a job to list all 3 last commits in the current directory and another one to count the total files in the current directory
name: List Commits and PRs
on:
  push:
    branches:
      - main

jobs:
  list_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List commits
        run: |
          echo "Listing the last 3 commits in the current directory:"
          git log -3 --oneline

  count_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count files
        run: |
          echo "Counting the total number of files in the current directory:"
          find . -type f | wc -l
