# generate a job to list the minor size file in the repo and the major size file
name: List file size
on:
  push:
    branches:
      - main

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List largest files
        run: |
          echo "Listing the largest files in the repository:"
          find . -type f -exec du -h {} + | sort -rh | head -n 10

      - name: List smallest files
        run: |
          echo "Listing the smallest files in the repository:"
          find . -type f -exec du -h {} + | sort -rh | tail -n 10
